### ISSUE TITLE
Add `data sink` class.

### ISSUE THREAD

**Issue by MaHaWo** [ssciwr/iSparrow#25]
System will communicate results over the network. A `DataSink` class would abstract away what happens with the detection results after they have been created and would thus help with modularization. 
Not yet sure whether this is 'overengineering', it seems easy enough given that we have to the 'hard' ssh stuff anyway.

- Trivial data sink: receive data, write to folder as csv 
- Nontrivial: send over ssh connection to remote.

**Comment by iulusoy** [comment]
Would handle the `csv` writing by a runner and the data communication by a separate smaller package that is tailored to each specific technical solution.
